CURRICULUM = {
    "Chemistry": [
        {"n": 1, "title": "Separation of Mixtures and Purification of Chemical Substances",
         "objectives": ["Distinguish between elements, compounds and mixture", "Differentiate between chemical and physical changes", "Distinguish between pure and impure substances", "Use boiling and melting points as criteria for purity", "Identify the properties of the components of a mixture", "Specify the principle involved in each separation method", "Apply separation principles in everyday life"],
         "subtopics": ["Elements, compounds and mixtures", "Chemical and physical changes", "Pure and impure substances", "Boiling, density, freezing and melting points", "Separation processes: evaporation, simple and fractional distillation, sublimation, re-crystallization, paper and column chromatography, simple and fractional crystallization, magnetization, decantation, filtration and centrifugation"]},
        {"n": 2, "title": "Chemical Combination",
         "objectives": ["Deduce the chemical laws from given data", "Perform calculations involving formulae, equations and mole concept", "Deduce stoichiometry of chemical reactions"],
         "subtopics": ["Laws of definite, multiple and reciprocal proportions", "Law of conservation of matter"]},
        {"n": 3, "title": "Kinetic Theory of Matter and Gas Laws",
         "objectives": ["Apply the theory to distinguish solids, liquids and gases", "Deduce reasons for change of state", "Draw inferences based on molecular motion", "Deduce gas laws from expressions", "Interpret graphical representations", "Perform calculations based on gas laws", "State factors responsible for deviation of real gases"],
         "subtopics": ["Phenomena supporting kinetic theory: melting, vapourization, boiling, freezing, condensation, Brownian movement", "Laws of Boyle, Charles, Avogadro, Gay-Lussac, Graham and Dalton", "The ideal gas equation PV = nRT", "Vapour density and relative molecular mass", "Ideal and real gases"]},
        {"n": 4, "title": "Atomic Structure and Bonding",
         "objectives": ["Distinguish between atoms, molecules and ions", "Identify contributions of Dalton, Millikan, Rutherford, Moseley, Thompson and Bohr", "Deduce protons, neutrons and electrons from atomic and mass numbers", "Apply rules for electron arrangement", "Identify common elements exhibiting isotopy", "Relate isotopy to mass number", "Perform calculations on isotopy", "Differentiate shapes of orbitals", "Determine electrons in s and p orbitals", "Relate atomic number to periodic position", "Relate group properties", "Identify reasons for variations in properties", "Differentiate bonding types", "Deduce bond types from electron configurations", "Relate bonding to properties of compounds", "Differentiate molecule shapes"],
         "subtopics": ["Concept of atoms, molecules and ions", "Works of Dalton, Millikan, Rutherford, Moseley, Thompson and Bohr", "Atomic structure, four quantum numbers, electron configuration", "Chemical symbols, formulae, equations", "Relative atomic mass based on 12C=12", "Mole concept and stoichiometry", "Periodic table and periodicity", "Ionization energy, ionic radii, electron affinity, electronegativity", "Chemical bonding: electrovalency and covalency", "Coordinate bond complexes", "Van der Waals forces", "Shapes of molecules: linear, non-linear, tetrahedral, pyramidal"]},
        {"n": 5, "title": "Nuclear Chemistry",
         "objectives": ["Distinguish chemical from nuclear reactions", "Differentiate natural and artificial radioactivity", "Compare properties of nuclear radiations", "Compute half-life calculations", "Balance nuclear equations", "Identify applications of radioactivity"],
         "subtopics": ["Radioactivity - types, properties and detection", "Natural and artificial radioactivity", "Nuclear stability and radioactive decay", "Nuclear reactions: fusion and fission", "Applications of radioactivity", "Half-life calculations"]},
        {"n": 6, "title": "Solubility",
         "objectives": ["Distinguish types of solutions", "Interpret solubility curves", "Calculate solute dissolved at given temperature", "Deduce solubility is temperature-dependent", "Relate solvents to their uses", "Differentiate true solutions, suspensions and colloids", "Compare properties of true and false solutions", "Provide examples of suspensions and colloids"],
         "subtopics": ["Unsaturated, saturated and supersaturated solutions", "Solubility curves", "Solubility in mol/dm3", "Solvents for fats, oil, perspiration and paints", "True and false solutions (suspensions and colloids)", "Examples: Harmattan haze, water paints, fog, milk, blood, aerosol spray, emulsion paints, rubber solution"]},
        {"n": 7, "title": "Environmental Pollution",
         "objectives": ["Give reasons for air as a mixture", "Identify principle for separating air components", "State reasons for variation in air composition", "Specify uses of air constituents", "Identify pollution types and pollutants", "Specify sources of pollutants", "Classify pollutants as biodegradable or not", "Specify effects of pollution", "Identify control measures"],
         "subtopics": ["Air: natural gaseous constituents and proportions", "Factors responsible for variation of air components", "Air as a mixture and uses of noble gases", "Air pollution: H2S, CO, SO2, oxides of nitrogen, CFCs, dust", "Sources and effects of pollutants", "Water pollution: sewage and oil pollution", "Soil pollution: oil spillage, biodegradable and non-biodegradable pollutants"]},
        {"n": 8, "title": "Acids, Bases and Salts",
         "objectives": ["Distinguish properties of acids and bases", "Identify types of acids and bases", "Determine basicity of acids", "Differentiate acidity and alkalinity", "Identify preparation methods of salts", "Classify types of salts", "Relate dissociation to strength", "Relate dissociation to conductance", "Perform pH and pOH calculations", "Enumerate significance of pH", "State applications of buffers", "Identify appropriate indicators", "Interpret titration curves", "Perform mole calculations", "Balance hydrolysis equations", "Deduce acidic, basic or neutral properties"],
         "subtopics": ["General characteristics, properties and uses of acids, bases and salts", "Acid/base indicators and basicity of acids", "Normal, acidic, basic and double salts", "Acids as proton donors; H3O+ ions", "Ethanoic, citric and tartaric acids", "Alums as double salts", "Preparation of salts by neutralization, precipitation, action of acids on metals", "Oxides and trioxocarbonate (IV) salts", "Conductance of strong and weak acids/bases", "pH and pOH scale", "Buffer solutions", "Acid/base titrations", "Hydrolysis of salts: NH4Cl, AlCl3, Na2CO3, CH3COONa"]},
        {"n": 9, "title": "Oxidation and Reduction - Redox",
         "objectives": ["Identify forms of expressing oxidation and reduction", "Classify reactions as oxidation or reduction", "Balance redox equations", "Deduce oxidation number of species", "Compute electron transfer in redox", "Identify redox species in reactions", "Distinguish oxidizing and reducing agents", "Apply oxidation number in naming", "Relate reagents to oxidizing and reducing abilities"],
         "subtopics": ["Oxidation in terms of addition of oxygen", "Reduction as removal of oxygen", "Oxidation and reduction in terms of electron transfer", "Use of oxidation numbers", "IUPAC nomenclature using oxidation number", "Tests for oxidizing and reducing agents"]},
        {"n": 10, "title": "Electrolysis",
         "objectives": ["Distinguish electrolytes and non-electrolytes", "Perform Faraday calculations", "Identify suitable electrodes", "Specify chemical reactions at electrodes", "Determine products at electrodes", "Identify factors affecting electrolysis", "Specify applications of electrolysis", "State significance of electrochemical series", "Identify electrochemical cells", "Calculate electrode potentials", "Determine electrolytic applications", "Identify metal protection methods"],
         "subtopics": ["Electrolytes and non-electrolytes", "Faraday laws of electrolysis", "Electrolysis of dilute H2SO4, aqueous CuSO4, CuCl2, NaCl solutions, fused NaCl", "Factors affecting discharge of ions", "Uses: purification of metals, production of Al, Na, O2, Cl2, NaOH", "Electrochemical cells: electrochemical series", "Half-cell reactions and electrode potentials", "Corrosion as electrolytic process", "Cathodic protection, painting, electroplating, coating with grease or oil"]},
        {"n": 11, "title": "Energy Changes",
         "objectives": ["Determine heat changes in processes", "Interpret graphical representations of heat changes", "Relate physical state to orderliness", "Determine conditions for spontaneity", "Relate dH, dS and dG as driving forces", "Solve problems on dG = dH - T dS"],
         "subtopics": ["Energy changes in physical and chemical changes", "Dissolution of substances in water", "Endothermic and exothermic reactions", "Entropy as order-disorder phenomenon", "Spontaneity: dG = 0, dG greater or less than zero", "dG = dH - T dS"]},
        {"n": 12, "title": "Rates of Chemical Reaction",
         "objectives": ["Identify factors affecting reaction rates", "Determine effects of temperature", "Examine effect of concentration/pressure", "Describe effect of surface area", "Determine suitable catalysts", "Determine ways to moderate effects", "Interpret reaction rate curves", "Solve problems on rates", "Relate rate to kinetic theory", "Examine significance of activation energy", "Deduce activation energy from curves"],
         "subtopics": ["Effect of temperature on reaction rate", "Effect of concentration/pressure", "Effect of surface area", "Effect of catalyst", "Reaction rate curves", "Activation energy", "Arrhenius law and collision theory", "Effect of light on some reactions"]},
        {"n": 13, "title": "Chemical Equilibria",
         "objectives": ["Identify factors affecting equilibrium position", "Predict effects of each factor", "Specify industrial processes using Le Chatelier principle", "Determine effects on equilibrium constant"],
         "subtopics": ["Reversible reactions", "Factors governing equilibrium position", "Dynamic equilibrium", "Le Chatelier principle and industrial applications", "Equilibrium constant"]},
        {"n": 14, "title": "Non-Metals and their Compounds",
         "objectives": ["Predict reagents for preparations", "Identify properties of gases and compounds", "Compare properties", "Specify uses of gases", "Determine specific tests", "Identify allotropes of oxygen", "Determine significance of ozone", "Classify oxides", "Identify uses of water", "Identify effects of dissolved gases", "Distinguish hard and soft water", "Determine causes of hardness", "Identify removal methods", "Describe water treatment"],
         "subtopics": ["Hydrogen: commercial production, lab preparation, properties, uses, test", "Halogens: Chlorine - preparation, properties, uses", "Hydrogen chloride and Hydrochloric acid", "Oxygen: lab preparation, properties, uses", "Oxides: acidic, basic, amphoteric, neutral", "Ozone and importance in atmosphere", "Water: composition, solvent, atmospheric gases, hard and soft water, treatment", "Sulphur: allotropes, SO2, H2SO3, H2SO4, H2S", "Nitrogen: lab preparation, ammonia (Haber), ammonium salts, HNO3, nitrogen cycle", "Carbon: allotropes, CO2, CO, coal, coke, synthesis gas"]},
        {"n": 15, "title": "Metals and their Compounds",
         "objectives": ["Specify general properties of metals", "Determine suitable extraction methods", "Relate methods to metal properties", "Compare metal reactivities", "Specify metal uses", "Determine tests for metallic ions", "Determine compound production processes", "Compare compound reactivities", "Specify compound uses", "Specify composition of cement", "Describe bauxite purification", "Specify ores of tin", "Identify transition metal properties", "Deduce reasons for transition properties", "Determine IUPAC names of complexes", "Determine iron extraction method", "Specify iron properties and uses", "Identify forms of iron", "Identify copper extraction method", "Relate copper properties to uses", "Specify CuSO4 preparation", "Specify alloy constituents and uses", "Compare alloys to pure metals"],
         "subtopics": ["General properties of metals", "Alkali metals (sodium): NaOH, Na2CO3, NaCl", "Alkaline-earth metals (calcium): CaO, Ca(OH)2, CaCO3, cement", "Aluminium: purification of bauxite, electrolytic extraction", "Tin: extraction from ores", "First transition series: electron configuration, oxidation states, complex ions, colour, catalysis", "Iron: extraction, properties, forms, steel", "Copper: extraction, properties, CuSO4, test", "Alloys: steel, stainless steel, brass, bronze, type-metal, duralumin, soft solder, permalloy, alnico"]},
        {"n": 16, "title": "Organic Compounds",
         "objectives": ["Derive names from general formulae", "Relate name to structure", "Relate tetravalency to catenation", "Classify by functional groups", "Derive empirical and molecular formulae", "Relate structure to properties", "Derive isomeric forms", "Distinguish types of isomerism", "Classify hydrocarbons", "Distinguish hydrocarbon classes", "Specify uses of hydrocarbons", "Identify crude oil as complex mixture", "Relate fractions to properties and uses", "Relate transformations to quality improvement", "Distinguish polymerization processes", "Specify vulcanization process", "Specify tests for alkenes", "Specify tests for terminal alkynes", "Distinguish aliphatic and aromatic hydrocarbons"],
         "subtopics": ["Tetravalency of carbon, general formula, IUPAC nomenclature", "Alkanes: homologous series, substitution, isomerism, petroleum, cracking, reforming, octane number", "Alkenes: isomerism, addition, polymerization, polythene, synthetic rubber, vulcanization", "Alkynes: ethyne production, reactions, properties", "Aromatic hydrocarbons: benzene structure, properties, uses", "Alkanols: primary, secondary, tertiary, ethanol production, Lucas test", "Alkanals and alkanones: chemical tests", "Alkanoic acids: neutralization, esterification", "Alkanoates: formation, fats and oils, saponification, soap, margarine", "Amines: primary, secondary, tertiary", "Carbohydrates: mono-, di-, polysaccharides, tests, hydrolysis, uses", "Proteins: structure, hydrolysis, tests, enzymes", "Polymers: natural and synthetic rubber, addition and condensation polymerization, thermoplastics, thermosetting plastics"]},
        {"n": 17, "title": "Chemistry and Industry",
         "objectives": ["Classify chemical industries by products", "Identify raw materials for each", "Distinguish fine and heavy chemicals", "Enumerate relevance of each industry", "Relate industrial processes to biotechnology"],
         "subtopics": ["Chemical industries: types, raw materials and relevance", "Biotechnology"]},
        {"n": 18, "title": "Astronomical Chemistry",
         "objectives": ["State composition of the solar system", "List the planets", "Identify segments of the earth", "Name natural satellite of the earth", "Identify smallest planet farthest from the sun"],
         "subtopics": ["Solar system, planets, satellite", "Composition of the earth: atmosphere, lithosphere, hydrosphere"]}
    ],
    "Mathematics": [
        {"n": 1, "title": "Number Bases and Modular Arithmetic",
         "objectives": ["Perform four basic operations on numbers", "Convert from one base to another", "Perform operations in modulo arithmetic"],
         "subtopics": ["Operations in different number bases from 2 to 10", "Conversion from one base to another including fractional parts", "Modular arithmetic"]},
        {"n": 2, "title": "Fractions, Decimals, Approximations and Percentages",
         "objectives": ["Perform basic operations on fractions and decimals", "Express to specified number of significant figures and decimal places", "Calculate simple interest, profit and loss percent, ratio, proportion, rate and percentage error", "Solve problems involving share and VAT"],
         "subtopics": ["Fractions and decimals", "Significant figures", "Decimal places", "Percentage errors", "Simple interest", "Profit and loss percent", "Ratio, proportion and rate", "Shares and Value Added Tax (VAT)"]},
        {"n": 3, "title": "Indices, Logarithms and Surds",
         "objectives": ["Apply laws of indices in calculation", "Establish relationship between indices and logarithms", "Solve equations involving indices", "Solve problems in different bases in logarithms", "Simplify and rationalize surds", "Perform basic operations on surds"],
         "subtopics": ["Laws of indices", "Equations involving indices", "Standard form", "Laws of logarithm", "Logarithm of any positive number to a given base", "Change of bases in logarithm", "Relationship between indices and logarithm", "Surds"]},
        {"n": 4, "title": "Sets",
         "objectives": ["Identify types of sets: empty, universal, complements, subsets, finite, infinite, disjoint", "Solve problems involving cardinality of sets", "Solve set problems using symbols", "Use Venn diagrams to solve problems involving not more than 3 sets"],
         "subtopics": ["Types of sets", "Algebra of sets", "Venn diagrams and their applications"]},
        {"n": 5, "title": "Polynomials",
         "objectives": ["Find the subject of the formula of a given equation", "Apply factor and remainder theorem to factorize expressions", "Multiply and divide polynomials of degree not more than 3", "Factorize by regrouping, difference of two squares, perfect squares, cubic expressions", "Solve simultaneous equations - one linear, one quadratic", "Interpret graphs of polynomials including applications to maximum and minimum"],
         "subtopics": ["Change of subject of formula", "Addition, subtraction, multiplication and division of polynomials", "Factorization of polynomials of degree not exceeding 3", "Roots of polynomials not exceeding degree 3", "Factor and remainder theorems", "Simultaneous equations including one linear one quadratic", "Graphs of polynomials of degree not greater than 3"]},
        {"n": 6, "title": "Variation",
         "objectives": ["Solve problems involving direct, inverse, joint and partial variations", "Solve problems on percentage increase and decrease in variation"],
         "subtopics": ["Direct variation", "Inverse variation", "Joint variation", "Partial variation", "Percentage increase and decrease"]},
        {"n": 7, "title": "Inequalities",
         "objectives": ["Solve problems on linear and quadratic inequalities", "Interpret graphs of inequalities"],
         "subtopics": ["Analytical and graphical solutions of linear inequalities", "Quadratic inequalities with integral roots only"]},
        {"n": 8, "title": "Progression",
         "objectives": ["Determine the nth term of a progression", "Compute the sum of A.P. and G.P.", "Sum to infinity of a given G.P."],
         "subtopics": ["nth term of a progression", "Sum of A.P. and G.P.", "Sum to infinity"]},
        {"n": 9, "title": "Binary Operations",
         "objectives": ["Solve problems involving closure, commutativity, associativity and distributivity", "Solve problems involving identity and inverse elements"],
         "subtopics": ["Properties of closure, commutativity, associativity and distributivity", "Identity and inverse elements (simple cases only)"]},
        {"n": 10, "title": "Matrices and Determinants",
         "objectives": ["Perform basic operations on matrices", "Calculate determinants", "Compute inverses of 2x2 matrices"],
         "subtopics": ["Algebra of matrices not exceeding 3x3", "Determinants of matrices not exceeding 3x3", "Inverses of 2x2 matrices"]},
        {"n": 11, "title": "Euclidean Geometry",
         "objectives": ["Identify various types of lines and angles", "Solve problems involving polygons", "Calculate angles using circle theorems", "Identify construction procedures of special angles (30, 45, 60, 75, 90, etc.)"],
         "subtopics": ["Properties of angles and lines", "Polygons: triangles, quadrilaterals and general polygons", "Circles: angle properties, cyclic quadrilaterals and intersecting chords", "Construction"]},
        {"n": 12, "title": "Mensuration",
         "objectives": ["Calculate perimeters and areas of triangles, quadrilaterals, circles and composite figures", "Find length of arc, chord, perimeters and areas of sectors and segments", "Calculate total surface areas and volumes of cuboids, cylinders, cones, pyramids, prisms, spheres and composite figures", "Determine distance between two points on the earth's surface"],
         "subtopics": ["Lengths and areas of plane geometrical figures", "Lengths of arcs and chords of a circle", "Perimeters and areas of sectors and segments of circles", "Surface areas and volumes of simple solids and composite figures", "The earth as a sphere: longitudes and latitudes"]},
        {"n": 13, "title": "Loci",
         "objectives": ["Identify and interpret loci relating to parallel lines, perpendicular bisectors, angle bisectors and circles"],
         "subtopics": ["Locus in 2 dimensions based on geometric principles relating to lines and curves"]},
        {"n": 14, "title": "Coordinate Geometry",
         "objectives": ["Determine midpoint and gradient of a line segment", "Find distance between two points", "Identify conditions for parallelism and perpendicularity", "Find equation of a line in two-point form, point-slope form, slope-intercept form and general form"],
         "subtopics": ["Midpoint and gradient of a line segment", "Distance between two points", "Parallel and perpendicular lines", "Equations of straight lines"]},
        {"n": 15, "title": "Trigonometry",
         "objectives": ["Calculate sine, cosine and tangent of angles between -360 and 360 degrees", "Apply special angles (30, 45, 60, 75, 90, 105, 135) to solve problems", "Solve problems involving angles of elevation and depression", "Solve problems involving bearings", "Apply trigonometric formulae to find areas of triangles", "Solve problems involving sine and cosine graphs"],
         "subtopics": ["Trigonometric ratios of angles", "Angles of elevation and depression", "Bearings", "Areas and solutions of triangle", "Graphs of sine and cosine", "Sine and cosine formulae"]},
        {"n": 16, "title": "Differentiation",
         "objectives": ["Find the limit of a function", "Differentiate explicit algebraic and simple trigonometric functions"],
         "subtopics": ["Limit of a function", "Differentiation of explicit algebraic and simple trigonometric functions (sine, cosine, tangent)"]},
        {"n": 17, "title": "Application of Differentiation",
         "objectives": ["Solve problems involving applications of rate of change, maxima and minima"],
         "subtopics": ["Rate of change", "Maxima and minima", "Applications to real problems"]},
        {"n": 18, "title": "Integration",
         "objectives": ["Solve problems of integration involving algebraic and simple trigonometric functions", "Calculate area under the curve (simple cases only)"],
         "subtopics": ["Integration of explicit algebraic and simple trigonometric functions", "Area under the curve"]},
        {"n": 19, "title": "Representation of Data",
         "objectives": ["Identify and interpret frequency distribution tables", "Interpret information on histogram, bar chart and pie chart"],
         "subtopics": ["Frequency distribution", "Histogram, bar chart and pie chart"]},
        {"n": 20, "title": "Measures of Location",
         "objectives": ["Calculate the mean, mode and median of ungrouped and grouped data (simple cases only)", "Use Ogive to find median, quartiles and percentiles"],
         "subtopics": ["Mean, mode and median of ungrouped and grouped data (simple cases only)", "Cumulative frequency"]},
        {"n": 21, "title": "Measures of Dispersion",
         "objectives": ["Calculate the range, mean deviation, variance and standard deviation of ungrouped and grouped data"],
         "subtopics": ["Range", "Mean deviation", "Variance", "Standard deviation"]},
        {"n": 22, "title": "Permutation and Combination",
         "objectives": ["Solve simple problems involving permutation and combination"],
         "subtopics": ["Linear and circular arrangements", "Arrangements involving repeated objects"]},
        {"n": 23, "title": "Probability",
         "objectives": ["Solve simple problems in probability including addition and multiplication"],
         "subtopics": ["Experimental probability (tossing of coin, throwing of dice, etc.)", "Addition and multiplication of probabilities (mutual and independent cases)"]}
    ]
}
