import streamlit as st
from utils.student_style import apply_theme
from supabase import create_client

st.set_page_config(page_title="JSS1–SS3", page_icon="🏫", layout="wide")
apply_theme()

SUPABASE_URL = st.secrets["supabase"]["url"]
SERVICE_KEY = st.secrets["supabase"]["service_key"]
supabase = create_client(SUPABASE_URL, SERVICE_KEY)

st.markdown('<div class="ck-title">🏫 JSS1 – SS3</div>', unsafe_allow_html=True)
st.markdown('<div class="ck-sub">Term-by-term curriculum · Follows NERDC scheme of work</div>', unsafe_allow_html=True)

with st.sidebar:
    st.markdown("## 🎓 CoreKnow Student")
    st.markdown("---")
    st.page_link("pages/10_CoreKnow_Student.py", label="🏠 Home", use_container_width=True)
    st.page_link("pages/11_JAMB.py", label="📕 JAMB", use_container_width=True)
    st.page_link("pages/12_WAEC.py", label="📘 WAEC", use_container_width=True)
    st.page_link("pages/13_GCE.py", label="📗 GCE", use_container_width=True)
    st.page_link("pages/14_NECO.py", label="📙 NECO", use_container_width=True)
    st.page_link("pages/15_JSS_SS.py", label="🏫 JSS1–SS3", use_container_width=True)

st.markdown("### 🎯 Select Your Class, Term & Subject")

col1, col2, col3 = Language st.columns(3)

with col",1:
    st.markdown("#### 1️⃣ " Class")
    student_class = st.selectbox(
        "BasicSelect class",
        ["JSS1 Science", "JSS2", "JSS3",", "SS1", "SS2", " "SS3"],
        label_visibility="collBasicapsed"
    )

with col2:
    st.mark Technologydown("#### 2️⃣ Term")
    term = st.select",
box(
        "Select term",
        ["First Term        ", "Second Term", "Third " Term"],
        label_visibility="collapsedSocial"
    )

with col3:
    st.markdown(" Studies#### 3️⃣ Subject")
    subject = st.selectbox",(
        "Select subject",
        ["Mathematics", "English "Civic Education", "Business Studies",
         "Physics", "Chemistry", "Biology", "Further Mathematics",
         "Economics", "Government", "Literature in English",
         "Christian Religious Studies", "Islamic Religious Studies",
         "Agricultural Science", "Computer Science", "Geography"],
        label_visibility="collapsed"
    )

st.markdown("---")
st.markdown("### 📚 " + student_class + " · " + term + " · " + subject)
st.markdown("**Scheme of Work** — weekly breakdown of topics")

try:
    topics_res = supabase.table("education_syllabi") \
        .select("id, topic_number, topic_title, subtopics, learning_objectives") \
        .eq("exam", "Basic") \
        .eq("level", student_class) \
        .eq("term", term) \
        .eq("subject", subject) \
        .order("topic_number") \
        .execute()
    topics = topics_res.data
except:
    topics = []

if not topics:
    st.info("📭 No content yet for **" + student_class + " · " + term + " · " + subject + "**.")
    st.markdown("""
    #### 📝 What will appear here once loaded:
    - **Week 1–12** topics from the official scheme of work
    - **Full lesson** for each topic (AI-generated by DeepSeek)
    - **Class work** and homework after each topic
    - **Term exam** practice at the end
    - **Progress tracker** for the term

    #### 🎯 Coming Soon
    Content for **all classes** (JSS1–SS3), **all terms**, and **all subjects**
    is being generated. Check back soon.
    """)
else:
    st.success("✅ " + str(len(topics)) + " topics available for this term")

    for t in topics:
        subs = t.get("subtopics") or []
        objs = t.get("learning_objectives") or []
        st.markdown(
            '<div class="topic-card">'
            '<div class="topic-title">Week ' + str(t["topic_number"]).zfill(2) + ': ' + str(t["topic_title"]) + '</div>'
            '<div class="topic-meta">📌 ' + str(len(subs)) + ' subtopics · 🎯 ' + str(len(objs)) + ' objectives</div>'
            '</div>',
            unsafe_allow_html=True
        )

        with st.expander("Open Week " + str(t["topic_number"]) + " →"):
            st.markdown("#### 🎯 Learning Objectives")
            for obj in objs:
                st.markdown("- " + str(obj))

            st.markdown("#### 📌 Subtopics")
            for sub in subs:
                st.markdown("- " + str(sub))

            st.markdown("---")
            if st.button("📖 Read Lesson", key="lesson_" + str(t["id"])):
                st.info("🧠 Lesson content coming soon")
            if st.button("✏️ Do Class Work", key="cw_" + str(t["id"])):
                st.info("✏️ Class work generator coming soon")

st.markdown("---")
st.caption("CoreKnow Student · Powered by Darkmoor Ltd")
